name: First Workflow
on: [ workflow_dispatch, push ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Done - bye"
      - name: Give error
        run: exit 1